### PR TITLE
Ascraeusrupack c61 v2

### PR DESCRIPTION
**Pull request by c6l**
Second version of branch. With "ширина не более"... etc.

### CODE REVIEW

**Comment by rxu** [comment]
Second pull request is not needed. When you commit to the same branch you have requested pull before, the pull request is updated.

**Comment by c6l** [comment]
This way let's delete second branch (v2)

Inet problems. Github pages loads very slowly. Can't nothing to do.

**Comment by rxu** [comment]
Closing it is enough, no problem.

**Comment by c6l** [comment]
Ooops!... First brunch has been deleted, not second. My mistake) I'd like to delete all my branches. No problems ? I see, pull request has been merged.

**Pull request closed without merging**
